version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -U pip
            pip install "mkdocs>=0.17.1,<0.18.0"
            mkdocs gh-deploy --clean
