version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/python:3
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "21:f2:d0:5c:0c:86:73:88:3a:59:2c:e1:02:6a:14:80"
      - run:
          name: Deploy
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -U pip
            pip install "mkdocs>=0.17.1,<0.18.0"
            mkdocs gh-deploy --clean
